name: Deploy
on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    env:
      TAG_NAME: '0.0.0'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
        
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Build
        run: mkdocs build
      
      - name: Set current tag
        run: |
          echo ${GITHUB_REF#refs/tags/}
          echo TAG_NAME=${GITHUB_REF#refs/tags/} >> $GITHUB_ENV
      
      - name: 'Compress Zip'
        run: |
          zip -r "manpi_release_${{ env.TAG_NAME }}.zip" \
          site/ \
          
      - name: Download QShell
        run: |
          wget -O qshell.tar.gz $(curl -s https://api.github.com/repos/qiniu/qshell/releases/latest | jq -r '.assets[] | select(.name | test("linux-amd64.tar.gz$")) | .browser_download_url')
          tar -xzf qshell.tar.gz

      - name: Upload to Qiniu
        run: |
          ${{ github.workspace }}/qshell account ${{ secrets.CI_CDN_ACCESS_KEY }} ${{ secrets.CI_CDN_SECRET_KEY }} manpi
          ${{ github.workspace }}/qshell qupload2 --src-dir=${{ github.workspace }}/site --bucket=${{ secrets.CI_CDN_BUCKET }} --overwrite=true
      
      - name: Create a new release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body_path: ${{ github.workspace }}/docs/about/changelog.md
          files: manpi_release_${{ env.TAG_NAME }}.zip
